# Key settings (must edit)
project_title: KD5081 Checklist
project_repo: lucydot/KD5081-Checklist
admins:
- lucydot
instructors:
- lucydot
- prakayastha
- r-pallister

students:
- lucydot
- r-pallister
- Tiskell
- Currentline
- Parker200019027
- mhoworth27
- kaitiea
- rumerharry
- Spacemandan88
- Dobbing01
- 22AlexScott22
- KLeniewski
- James1010101010
- Brandon-D-J
- sunildavis
- ac20035012
- Natcubby
- tbakiris
- kyleaff
- EpicEthanMoment
- VandaKiss
- PaigeTaylorA
- mat7hewm01
- WatsonJosh
- McLeodCharlie
- tazthedevil02
- HenryDerrick9274
- Declan-Pitt

web_address: https://lucydot.github.io/KD5081-Checklist

# User options (may edit)
questions: true
votes_required: 4
gh-pages: true
gh-pages_branch: gh-pages



